version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stationSkiDevops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nour94551467
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stationSkiDevops
      MYSQL_USER: root
      MYSQL_PASSWORD: nour94551467
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
